[package]
name = "appriori"
version = "0.1.0"
authors = ["Henrik Nygren <nygrenh@gmail.com>"]

[dependencies]
simple_parallel = "0.3"
num_cpus = "0.2"
# clippy = "*"
itertools = "0.4"
bit-vec = "0.4.3"
